### ISSUE TITLE
Flask Documentation PDF is missing

### ISSUE THREAD

**Issue by smorin** [mitsuhiko/flask#1460] opened 2015-05-14 05:35 UTC
Flask Documentation PDF is missing

Read the documentation or download as PDF and zipped HTML
Links to http://flask.pocoo.org/docs/flask-docs.pdf and http://flask.pocoo.org/docs/flask-docs.zip

Both of which are missing.

**Comment by davidism** [comment] 2015-05-14 06:36
Duplicate of pocoo/metaflask#7 and [all these](https://github.com/mitsuhiko/flask/issues?q=pdf).

**Comment by kierdwyn** [comment] 2015-06-01 20:25
Try this link:
https://media.readthedocs.org/pdf/flask/latest/flask.pdf

**Closed** 2015-09-10 21:53 UTC

**Comment by soerendip** [comment] 2019-06-23 13:51
The link is dead.
