### ISSUE TITLE
Core signals template_rendered doesn't works

### ISSUE THREAD

**Issue by ethe** [mitsuhiko/flask#1606] opened 2015-11-04 10:06 UTC
I try to subscribing a signal like this:
```python
def log_template_renders(sender, template, context, **extra):
    sender.logger.debug('Rendering template "%s" with context %s',
                        template.name or 'string template',
                        context)

from flask import template_rendered
template_rendered.connect(log_template_renders, app)
```
but it doesn't works. It must be like this:
```python
def log_template_renders(sender, template, context, **extra):
    sender.logger.debug('Rendering template "%s" with context %s',
                        template.name or 'string template',
                        context)

from flask import template_rendered

@forum.before_request
def before_request():
    template_rendered.connect(log_template_renders, app)
```
then it works well.

**Comment by mitsuhiko** [comment] 2015-11-04 10:35
Cannot reproduce. Can you provide a testcase?

**Comment by ethe** [comment] 2015-11-04 16:46
https://github.com/ethe/flask_testcase
I create a minimum application for this test, signal is imported in views. Only add the decorator `@testmodule.before_request` on signal can it works.

**Comment by ethe** [comment] 2015-11-04 17:33
Oops! I find out what mistake would I make. I'm sorry to disturb you

**Comment by mitsuhiko** [comment] 2015-11-04 17:37
Closing then :)

**Closed by mitsuhiko** 2015-11-04 17:37 UTC
