### ISSUE TITLE
Documentation PDF 404's on flask site

### ISSUE THREAD

**Issue by davidthewatson** [mitsuhiko/flask#1356] opened 2015-02-19 20:57 UTC
This link:

http://flask.pocoo.org/docs/flask-docs.pdf

on this page:

http://flask.pocoo.org/

Generates a 404.

**Comment by davidism** [comment] 2015-02-19 21:58
Duplicate of pocoo/metaflask#7 and [all these](https://github.com/mitsuhiko/flask/issues?q=is%3Aissue+is%3Aopen+documentation).

**Comment by pythonui** [comment] 2015-03-04 05:09
When its get fixed? Flask users really need this.... :)

**Closed** 2015-06-14 09:48 UTC
Labels: closing candidate, docs
