### ISSUE TITLE
documentation PDF link is dead

### ISSUE THREAD

**Issue by introvertmac** [mitsuhiko/flask#1375] opened 2015-03-11 22:18 UTC
got 404 for "download document as PDF"

**Comment by ThiefMaster** [comment] 2015-03-11 22:19
Duplicate of pocoo/metaflask#7

**Comment by charleswhchan** [comment] 2015-03-31 20:39
(Reminder before closing this ticket) 
Similar issue with "zipped HTML"

**Comment by keyan** [comment] 2015-03-31 20:42
@charleswhchan I am aware: #1300, #1333

**Comment by kierdwyn** [comment] 2015-06-01 20:28
Try this link for a PDF version documentation:
https://media.readthedocs.org/pdf/flask/latest/flask.pdf

**Comment by charleswhchan** [comment] 2015-06-01 20:38
Thanks @kierdwyn.

... now we just need to update the link in the welcome doc:
http://flask.pocoo.org/

**Closed** 2015-06-14 09:48 UTC
Labels: closing candidate, docs
