### ISSUE TITLE
Documentation on Localtunnel link is invalid

### ISSUE THREAD

**Issue by gerrat** [mitsuhiko/flask#1713] opened 2016-02-01 22:38 UTC
The bottom of the [quickstart](http://flask.pocoo.org/docs/0.10/quickstart/#quickstart) page has a link: [Sharing your Localhost Server with Localtunnel](http://flask.pocoo.org/snippets/89/)  to a page with old/outdated information on Localtunnel.  (it is pointing to Localtunnel [here](http://progrium.com/localtunnel/), which doesn't exist).

Localtunnel now appears to be: [here](https://localtunnel.me/) or on github [here](https://github.com/localtunnel/localtunnel), and is installed via `npm`, not `gem`.

**Comment by davidism** [comment] 2016-02-01 22:41
That is a community snippet, not part of the Flask documentation.  It can only be modified by the author or an admin.  Duplicate of mitsuhiko/flask-website#15, which will be closed as soon as I get site permissions.

**Closed by davidism** 2016-02-01 22:41 UTC
