### ISSUE TITLE
Any plans for new versions? Maybe 1.0?

### ISSUE THREAD

**Issue by surrealcristian** [mitsuhiko/flask#1518] opened 2015-06-25 18:13 UTC
Hello everybody.

Please, forgive my poor english, and do not get me wrong, my question is not malicious.

Actually, are any plans to reach version 1.0? Or at least reach a new version?

1.0, or a more fluid release versions can be a way to attract more users and developers.

Greetings, and thanks for the work you do in Flask.

**Comment by davidism** [comment] 2015-06-25 19:57
Duplicate of #1492

**Closed** 2015-06-30 17:22 UTC
