### ISSUE TITLE
No wheel published

### ISSUE THREAD

**Issue by Yuav** [mitsuhiko/flask#1586] opened 2015-10-19 11:36 UTC
Please consider generating wheel for faster installs

http://pythonwheels.com/

**Comment by davidism** [comment] 2015-10-19 16:22
There is already some mention of wheels in [`setup.cfg`][1]  I'm marking this for 1.0, as it would make sense to be consistent with Werkzeug and Jinja.  We should check that other "first party" dependencies are consistent as well, for example itsdangerous.

[1]: https://github.com/mitsuhiko/flask/commit/b0bb6c7f3d2e80731428fcc50ab1edd45b58959d

**Comment by jeffwidman** [comment] 2015-11-12 12:26
Dupe of #1350

**Comment by mitsuhiko** [comment] 2015-11-12 12:42
Closing this as duplicate.

**Closed by mitsuhiko** 2015-11-12 12:42 UTC
