### ISSUE TITLE
get_json raise on empty request body

### ISSUE THREAD

**Issue by stuxxn** [mitsuhiko/flask#1445] opened 2015-04-25 07:20 UTC
Dont know if this is a desired behavior, but if I send a request like this:
> Content-Type: application/json
> Content-Length: 0

and access `get_json` it raises a 'Cant not decode' error.
Imho it would be better to just return `None` as if `is_json == False`.

Working with: Flask 0.11.dev0

**Comment by untitaker** [comment] 2015-04-25 08:22
Duplicate of https://github.com/mitsuhiko/flask/issues/1317

**Closed by untitaker** 2015-04-25 08:22 UTC
