### ISSUE TITLE
Werkzeug 0.11 does not allow debug

### ISSUE THREAD

**Issue by ashleyscopes** [mitsuhiko/flask#1622] opened 2015-11-21 17:57 UTC
Running Flask, on Linux or Windows or OS X, if you run:

```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
    return "foo"

if __name__ == '__main__':
    app.run(debug=True)
```

...then python kills itself with an error (cant remember from top of my head...as I am not at my PC).

However, when you remove debug=True everything is fine.

Running # pip uninstall werkzeug

**Comment by ashleyscopes** [comment] 2015-11-21 18:00
... # pip install "werkzeug<0.11" ... fixes this issue.

I am new to this framework...so I apologise for this horrendous bug report. I just was wondering if I could have clarification. We are studying flask at uni and almost everyone has had this issue or others gettings Flask to install or run. Once it works, it is amazing. However, installation is a right pain.

Sorry for being vague. Hope this is of use to the devs of Flask.

Ashley

**Comment by mitsuhiko** [comment] 2015-11-21 18:30
I need to know the error you are getting otherwise I have to close this as cannot reproduce this.

**Comment by ashleyscopes** [comment] 2015-11-21 21:58
I have fixed it by installing Werkzeug 0.10.4 instead of 0.11. I am having to do coursework with Flask so I am not going to go out of my way to mess it up. All I can say is practically everyone in my year that I know have had one issue or another.
I have stumbled across this issue: https://github.com/mitsuhiko/werkzeug/issues/798 ... it is closed yet we are still having this issue.
Sorry for not being more help. I thought it would be better to at least make you aware that there is a potential issue rather than just ignoring it.
Thanks for the reply.
Ashley
On 21 Nov 2015 18:31, Armin Ronacher <notifications@github.com> wrote:I need to know the error you are getting otherwise I have to close this as cannot reproduce this.

**Comment by mitsuhiko** [comment] 2015-11-21 21:59
> All I can say is practically everyone in my year that I know have had one issue or another.

Unfortunately this reporting is not helpful. I need to know exactly which version of Werkzeug you were running as I cannot reproduce this. 0.11 is know to be broken but the latest version is 0.11.2 which has this bug to the best of our knowledge fixed.  Are you saying you have this issue with 0.11.2?

**Comment by ashleyscopes** [comment] 2015-11-21 22:07
Which ever version would have been installed with pip install flask just over a week ago.
I do not want to risk messing my install up. But if you are suggesting a new release has fixed the issue then please beg my pardon. I just wanted to alert you if you had not already known. I apologise for the hassle.
Thanks
On 21 Nov 2015 22:00, Armin Ronacher <notifications@github.com> wrote:
All I can say is practically everyone in my year that I know have had one issue or another.


Unfortunately this reporting is not helpful. I need to know exactly which version of Werkzeug you were running as I cannot reproduce this. 0.11 is know to be broken but the latest version is 0.11.2 which has this bug to the best of our knowledge fixed.  Are you saying you have this issue with 0.11.2?

**Closed** 2015-11-21 22:08 UTC
