### ISSUE TITLE
Documentation PDF version is not available

### ISSUE THREAD

**Issue by kalinchernev** [mitsuhiko/flask#1727] opened 2016-02-14 14:39 UTC
Hi, 

From home page, the link to the pdf version of the documentation should be http://flask.pocoo.org/docs/flask-docs.pdf but it's currently unavailable.

If the link is wrong, could you please provide a correct one?

**Comment by davidism** [comment] 2016-02-14 15:17
Duplicate of mitsuhiko/flask-website#16

**Closed by davidism** 2016-02-14 15:17 UTC

**Comment by kalinchernev** [comment] 2016-02-14 16:16
Thanks!
