### ISSUE TITLE
pkgutil.get_loader now throws errors on Python3.4

### ISSUE THREAD

**Issue by rawrgulmuffins** [mitsuhiko/flask#1481] opened 2015-06-06 00:47 UTC
In Python2.7 get_loader returns an empty string if a loader isn't found.

    $ python
    Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pkgutil
    >>> pkgutil.get_loader("testing")
    >>> pkgutil.get_loader(__name__)
    <pkgutil.ImpLoader instance at 0x7f03a435f8c0>
    >>> 

Python3.4 an AttributeError is thrown.

    $ python
    Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
    [GCC 4.8.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pkgutil
    >>> pkgutil.get_loader(__name__)
    <class '_frozen_importlib.BuiltinImporter'>
    >>> pkgutil.get_loader("testing")
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib/python3.4/pkgutil.py", line 467, in get_loader
        return find_loader(fullname)
    File "/usr/lib/python3.4/pkgutil.py", line 488, in find_loader
        return spec.loader
    AttributeError: 'NoneType' object has no attribute 'loader'
    >>> 

This means that if someone does something like

    from flask import Flask
    app = Flask("testing")

Then 

    AttributeError: 'NoneType' object has no attribute 'loader'

is thrown on Python3.4

Suggested changes in flask/flask/helpers.py 

in get_root_path

    637    # Next attempt: check the loader.
    638    loader = pkgutil.get_loader(import_name)

to 

    load =  None
    try:
        loader = pkgutil.get_loader(import_name)
    except AttributeError:
        pass

**Comment by untitaker** [comment] 2015-06-06 01:13
This is the same as https://github.com/mitsuhiko/flask/pull/1017.

I can't reproduce this issue with 3.4.3, but with 3.4.1 I can. So I think that this was a bug in Python that got fixed in a timely manner, and is unlikely to affect many users. Flask should not work around it.

**Closed by untitaker** 2015-06-06 01:13 UTC
