### ISSUE TITLE
feedback.flask.pocoo.org 404 page

### ISSUE THREAD

**Issue by AhnSeongHyun** [mitsuhiko/flask#1692] opened 2016-01-13 02:04 UTC
In http://flask.pocoo.org, "feedback website" link is 404 page. 

http://feedback.flask.pocoo.org/

**Comment by davidism** [comment] 2016-01-13 03:00
duplicate of mitsuhiko/flask-website#23

**Closed by davidism** 2016-01-13 03:00 UTC
