### ISSUE TITLE
CPU usage increase when debug=True running by virtualenv

### ISSUE THREAD

**Issue by coolcoca** [mitsuhiko/flask#1377] opened 2015-03-12 08:05 UTC
When I running a flask app with debug=True in virtualenv, the cpu usage increase to 20%. But if I set debug=False, the cpu usage is only 1%.
If I running without virtualenv, all is ok.

**Comment by davidism** [comment] 2015-03-12 13:27
Install the `watchdog` package when using the reloader, the built-in watcher is inefficient.

http://stackoverflow.com/questions/28241989/flask-app-restarting-with-stat/28242285#28242285

**Comment by coolcoca** [comment] 2015-03-13 06:14
fixed thank you.

**Comment by untitaker** [comment] 2015-03-18 23:27
Duplicate of https://github.com/mitsuhiko/werkzeug/issues/682

**Closed by untitaker** 2015-03-18 23:27 UTC
