### ISSUE TITLE
Documentation download links for PDF and zipped HTML return 404s on http://flask.pocoo.org/

### ISSUE THREAD

**Issue by bretellis** [mitsuhiko/flask#1736] opened 2016-02-22 15:47 UTC
I was trying to download the documentation from http://flask.pocoo.org/ using the PDF link and got a 404.  At the same time also tried the zipped HTML link and that returned a 404 as well.

**Comment by ThiefMaster** [comment] 2016-02-22 15:48
duplicate of mitsuhiko/flask-website#16

**Comment by bretellis** [comment] 2016-02-22 15:49
Thanks I searched first but didn't see that one.

**Closed** 2016-02-22 15:52 UTC
