### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by tigrafrog** [mitsuhiko/flask#1546] opened 2015-08-02 03:56 UTC
Hi, 
looks like you have some issues with website:
Documentation:
- http://flask.pocoo.org/docs/flask-docs.pdf returns 404
- http://flask.pocoo.org/docs/flask-docs.zip returns 404
- feedback.flask.pocoo.org "Server not found"

An main question (why I try to use "feedback"):
- Any plans to full Python 3 support?

**Comment by davidism** [comment] 2015-08-02 05:04
Duplicate of pocoo/metaflask#7 and [all these](https://github.com/mitsuhiko/flask/issues?q=pdf).

**Closed** 2015-10-31 21:03 UTC
Labels: closing candidate
