### ISSUE TITLE
PDF and zipped HTML doc links are broken in Flask homepage

### ISSUE THREAD

**Issue by marcosps** [mitsuhiko/flask#1556] opened 2015-08-19 17:00 UTC
Broken:
http://flask.pocoo.org/docs/flask-docs.pdf
http://flask.pocoo.org/docs/flask-docs.zip

Working:
http://flask.pocoo.org/docs/0.10/

**Comment by davidism** [comment] 2015-08-19 17:16
Duplicate of pocoo/metaflask#7 and [all these](https://github.com/mitsuhiko/flask/issues?q=pdf).

**Closed** 2015-10-31 21:39 UTC
